theme: jekyll-theme-cayman
title: Avinash Prasad
author: Avinash Prasad

avatar: "/assets/img/avatar-icon.png"

social-network-links:
  email: "avionmission@gmail.com"
  twitter: avionmission
  youtube: c/AvinashPrasad
